# -*- coding: utf-8 -*-
"""
Created on 2020/6/20 23:10

@Author: Mamba

@Purpose:

@ModifyRecord:
"""
DOMAIN_URL = "https://sh.lianjia.com/"

PATTERN = {
    "房间代号": "//property[@name = 'houseCode']/string/text()",
    "城市": "//property[@name = 'city_name']/string/text()",
    "小区": "//property[@name = 'resblockName']/string/text()",
    "lng": "//property[@name = 'resblockPosition']/string/text()",
    "lat": "//property[@name = 'resblockPosition']/string/text()",
    "单价": "/html/body/section[1]/div[2]/div[2]/div[1]/b/text()",
    "成交价格": "//html/body/section[1]/div[2]/div[2]/div[1]/span/i/text()",
    "挂牌价格": "/html/body/section[1]/div[2]/div[2]/div[3]/span[1]/label/text()",
    "挂牌时间": "/html/body/section[2]/div[1]/div[1]/div[1]/div[2]/div[2]/ul/li[3]/text()",
    "成交时间": "/html/body/div[4]/div/span/text()",
    "房屋户型": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[1]/text()",
    "房屋朝向": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[7]/text()",
    "所在楼层": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[2]/text()",
    "配备电梯": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[13]/text()",
    "装修情况": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[9]/text()",
    "建筑面积": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[3]/text()",
    "建筑类型": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[6]/text()",
    "建筑年代": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[8]/text()",
    "建筑结构": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[10]/text()",
    "梯户比例": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[12]/text()",
    "供暖方式": "/html/body/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul/li[11]/span/text()",
    "交易权属": "/html/body/section[2]/div[1]/div[1]/div[1]/div[2]/div[2]/ul/li[2]/text()",
    "房屋用途": "/html/body/section[2]/div[1]/div[1]/div[1]/div[2]/div[2]/ul/li[4]/text()",
    "房权所属": "/html/body/section[2]/div[1]/div[1]/div[1]/div[2]/div[2]/ul/li[6]/text()",
    "成交周期": "/html/body/section[1]/div[2]/div[2]/div[3]/span[2]/label/text()",
    "调价次数": "/html/body/section[1]/div[2]/div[2]/div[3]/span[3]/label/text()",
    "带看次数": "/html/body/section[1]/div[2]/div[2]/div[3]/span[4]/label/text()",
    "浏览次数": "/html/body/section[1]/div[2]/div[2]/div[3]/span[6]/label/text()",
    "关注人数": "/html/body/section[1]/div[2]/div[2]/div[3]/span[5]/label/text()",
    "成交小区均价": "/html/body/div[7]/div[1]/div[10]/div/div/div[2]/div/div[1]/span",
}

# 行政区域中文和拼音
NAMESPELLREGION1 = {
    "上海": "sh"
}
NAMESPELLREGION2 = {'上海周边': 'shanghaizhoubian',
                    '嘉定': 'jiading',
                    '奉贤': 'fengxian',
                    '宝山': 'baoshan',
                    '崇明': 'chongming',
                    '徐汇': 'xuhui',
                    '普陀': 'putuo',
                    '杨浦': 'yangpu',
                    '松江': 'songjiang',
                    '浦东': 'pudong',
                    '虹口': 'hongkou',
                    '金山': 'jinshan',
                    '长宁': 'changning',
                    '闵行': 'minhang',
                    '青浦': 'qingpu',
                    '静安': 'jingan',
                    '黄浦': 'huangpu'}

NAMESPELLREGION3 = {'七宝': 'qibao',
                    '万体馆': 'wantiguan',
                    '万祥镇': 'wanxiangzhen',
                    '万里': 'wanli',
                    '三林': 'sanlin',
                    '上大': 'shangda',
                    '上海南站': 'shanghainanzhan',
                    '上海周边': 'shanghaizhoubian2',
                    '不夜城': 'buyecheng',
                    '世博': 'shibo',
                    '世博滨江': 'shibobinjiang',
                    '东外滩': 'dongwaitan',
                    '中原': 'zhongyuan1',
                    '中山公园': 'zhongshangongyuan',
                    '中远两湾城': 'zhongyuanliangwancheng',
                    '丰庄': 'fengzhuang',
                    '临平路': 'linpinglu',
                    '临港新城': 'lingangxincheng',
                    '九亭': 'jiuting',
                    '书院镇': 'shuyuanzhen',
                    '五角场': 'wujiaochang',
                    '五里桥': 'wuliqiao',
                    '亭林': 'tinglin',
                    '人民广场': 'renminguangchang',
                    '仙霞': 'xianxia',
                    '佘山': 'sheshan',
                    '光新': 'guangxin',
                    '共富': 'gongfu',
                    '共康': 'gongkang',
                    '凉城': 'liangcheng',
                    '北外滩': 'beiwaitan',
                    '北新泾': 'beixinjing',
                    '北蔡': 'beicai',
                    '华东理工': 'huadongligong',
                    '华亭': 'huating',
                    '华新': 'huaxin',
                    '华泾': 'huajing',
                    '华漕': 'huacao',
                    '南京东路': 'nanjingdonglu',
                    '南京西路': 'nanjingxilu',
                    '南桥': 'nanqiao',
                    '南码头': 'nanmatou',
                    '南翔': 'nanxiang',
                    '南通': 'nantong',
                    '古北': 'gubei',
                    '古美': 'gumei',
                    '叶榭': 'yexie',
                    '合庆': 'geqing',
                    '吕巷': 'luxiang',
                    '启东': 'qidong1',
                    '吴泾': 'wujing',
                    '周家嘴路': 'zhoujiazuilu',
                    '周浦': 'zhoupu',
                    '唐镇': 'tangzhen',
                    '嘉兴': 'jiaxing',
                    '嘉定新城': 'jiadingxincheng',
                    '嘉定老城': 'jiadinglaocheng',
                    '四团': 'situan',
                    '四川北路': 'sichuanbeilu',
                    '堡镇': 'baozhen',
                    '塘桥': 'tangqiao',
                    '夏阳': 'xiayang',
                    '外冈': 'waigang',
                    '外高桥': 'waigaoqiao',
                    '大华': 'dahua',
                    '大团镇': 'datuanzhen',
                    '大场镇': 'dachangzhen',
                    '大宁': 'daning',
                    '天山': 'tianshan',
                    '太仓': 'taicang212',
                    '奉城': 'fengcheng',
                    '奉贤金汇': 'fengxianjinhui',
                    '安亭': 'anting',
                    '宣桥': 'xuanqiao',
                    '小昆山': 'xiaokunshan',
                    '山阳': 'shanyang',
                    '崇明其它': 'chongmingqita',
                    '崇明新城': 'chongmingxincheng',
                    '川沙': 'chuansha',
                    '常熟市': 'changshushi',
                    '庄行': 'zhuanghang',
                    '康健': 'kangjian',
                    '康桥': 'kangqiao',
                    '廊下': 'langxia',
                    '建国西路': 'jianguoxilu',
                    '张堰': 'zhangyan',
                    '张庙': 'zhangmiao',
                    '张江': 'zhangjiang',
                    '彭浦': 'pengpu',
                    '徐家汇': 'xujiahui',
                    '徐汇滨江': 'xuhuibinjiang',
                    '徐泾': 'xujing',
                    '徐行': 'xuxing',
                    '御桥': 'yuqiao1',
                    '惠南': 'huinan',
                    '打浦桥': 'dapuqiao',
                    '控江路': 'kongjianglu',
                    '斜土路': 'xietulu',
                    '新华路': 'xinhualu',
                    '新场': 'xinchang',
                    '新天地': 'xintiandi',
                    '新成路': 'xinchenglu1',
                    '新桥': 'xinqiao',
                    '新江湾城': 'xinjiangwancheng',
                    '新浜': 'xinbang',
                    '无锡市': 'wuxishi',
                    '昆山': 'kunshan1',
                    '春申': 'chunshen',
                    '曲阳': 'quyang',
                    '曹家渡': 'caojiadu',
                    '曹杨': 'caoyang',
                    '曹路': 'caolu',
                    '月浦': 'yuepu',
                    '朱家角': 'zhujiajiao',
                    '朱泾': 'zhujing',
                    '杨东': 'yangdong',
                    '杨思前滩': 'yangsiqiantan',
                    '杨行': 'yanghang',
                    '松江大学城': 'songjiangdaxuecheng',
                    '松江新城': 'songjiangxincheng',
                    '松江老城': 'songjianglaocheng',
                    '枫泾': 'fengjing',
                    '柘林': 'zhelin',
                    '桃浦': 'taopu',
                    '梅园': 'meiyuan1',
                    '梅陇': 'meilong',
                    '植物园': 'zhiwuyuan',
                    '横沙岛': 'hengshadao',
                    '武宁': 'wuning',
                    '永和': 'yonghe',
                    '江宁路': 'jiangninglu',
                    '江桥': 'jiangqiao',
                    '江湾镇': 'jiangwanzhen',
                    '泖港': 'maogang',
                    '泗泾': 'sijing',
                    '泥城镇': 'nichengzhen',
                    '洋泾': 'yangjing',
                    '浦江': 'pujiang1',
                    '海湾': 'haiwan',
                    '海门': 'haimen',
                    '淞南': 'songnan',
                    '淞宝': 'songbao',
                    '淮海中路': 'huaihaizhonglu',
                    '湖州': 'huzhou2',
                    '源深': 'yuanshen',
                    '漕河泾': 'caohejing',
                    '漕泾': 'caojing',
                    '潍坊': 'weifang',
                    '甘泉宜川': 'ganquanyichuan',
                    '田林': 'tianlin',
                    '白鹤': 'baihe',
                    '盈浦': 'yingpu',
                    '真光': 'zhenguang',
                    '真如': 'zhenru',
                    '石化': 'shihua',
                    '石湖荡': 'shihudang',
                    '碧云': 'biyun',
                    '祝桥': 'zhuqiao',
                    '练塘': 'liantang1',
                    '罗店': 'luodian',
                    '罗泾': 'luojing',
                    '老港镇': 'laogangzhen',
                    '老西门': 'laoximen',
                    '老闵行': 'laominhang',
                    '联洋': 'lianyang',
                    '航华': 'hanghua',
                    '航头': 'hangtou',
                    '花木': 'huamu',
                    '莘庄': 'xinzhuang5',
                    '莘闵别墅': 'shenminbieshu',
                    '菊园新区': 'juyuanxinqu',
                    '董家渡': 'dongjiadu',
                    '蓬莱公园': 'penglaigongyuan',
                    '虹桥': 'hongqiao1',
                    '衡山路': 'hengshanlu',
                    '西渡': 'xidu',
                    '西藏北路': 'xizangbeilu',
                    '西郊': 'xijiao',
                    '豫园': 'yuyuan',
                    '赵巷': 'zhaoxiang',
                    '车墩': 'chedun',
                    '通河': 'tonghe',
                    '重固': 'chonggu',
                    '金山': 'jinshan1',
                    '金杨': 'jinyang',
                    '金桥': 'jinqiao',
                    '金汇': 'jinhui',
                    '金泽': 'jinze',
                    '金虹桥': 'jinhongqiao',
                    '镇宁路': 'zhenninglu',
                    '长兴岛': 'changxingdao21211',
                    '长寿路': 'changshoulu',
                    '长征': 'changzheng',
                    '长桥': 'changqiao',
                    '长风': 'changfeng1',
                    '闸北公园': 'zhabeigongyuan',
                    '阳城': 'yangcheng',
                    '陆家嘴': 'lujiazui',
                    '陈家镇': 'chenjiazhen',
                    '青村': 'qingcun',
                    '静安寺': 'jingansi',
                    '静安新城': 'jinganxincheng',
                    '鞍山': 'anshan',
                    '顾村': 'gucun',
                    '颛桥': 'zhuanqiao',
                    '香花桥': 'xianghuaqiao',
                    '马桥': 'maqiao',
                    '马陆': 'malu',
                    '高东': 'gaodong',
                    '高境': 'gaojing',
                    '高行': 'gaohang',
                    '鲁迅公园': 'luxungongyuan',
                    '黄兴公园': 'huangxinggongyuan',
                    '黄浦滨江': 'huangpubinjiang',
                    '龙华': 'longhua',
                    '龙柏': 'longbai'}

region2_3 = {'上海周边': ['常熟市', '海门', '湖州', '嘉兴', '昆山', '南通', '启东', '上海周边', '太仓', '无锡市'],
             '嘉定': ['安亭', '丰庄', '华亭', '嘉定老城', '嘉定新城', '江桥', '菊园新区', '马陆', '南翔', '上大', '桃浦', '外冈',
                    '新成路', '徐行'], '奉贤': ['奉城', '奉贤金汇', '海湾', '南桥', '青村', '四团', '西渡', '柘林', '庄行'],
             '宝山': ['大场镇', '大华', '高境', '共富', '共康', '顾村', '罗店', '罗泾', '彭浦', '上大', '淞宝', '淞南', '通河',
                    '新江湾城', '杨行', '月浦', '张庙'], '崇明': ['堡镇', '长兴岛', '陈家镇', '崇明其它', '崇明新城', '横沙岛'],
             '徐汇': ['漕河泾', '长桥', '衡山路', '华东理工', ' 华泾', '建国西路', '康健', '龙华', '上海南站', '田林', '万体馆',
                    '斜土路', '徐汇滨江', '徐家汇', '植物园'],
             '普陀': ['曹杨', '长风', '长寿路', '长征', '甘泉宜川', '光新', '南翔', '桃浦', '万里', '武宁', '真光', '真如',
                    '中远两湾城'], '杨浦': ['鞍山', '东外滩', '黄兴公园', '控江路', '五角场', '新江湾城', '中原', '周家嘴路'],
             '松江': ['车墩', '九亭', '泖港', '莘闵别墅', '佘山', '石湖荡', '泗泾', '松江大学城', '松江老城', '松江新城', '小昆山',
                    '新浜', '新桥', '叶榭'],
             '浦东': ['北蔡', '碧云', '曹路', '川沙', '大团镇', '高东', '高行', '合庆', '航头', '花木', '惠南', '金桥', '金杨',
                    '康桥', '老港镇', '联洋', '临港新城', '陆家嘴', '梅园', '南码头', '泥城镇', '三林', '世博', '书院镇', '塘桥',
                    '唐镇', '外高桥', '万祥镇', '潍坊', '新场', '宣桥', '杨东', '洋泾', '杨思前滩', '源深', '御桥', '张江',
                    '周浦', '祝桥'],
             '虹口': ['北外滩', '大宁', '江湾镇', '凉城', '临平路', '鲁迅公园', '彭浦', '曲阳', '四川北路'],
             '金山': ['漕泾', '枫泾', '金山', '廊下', '吕巷', '山阳', '石化', '亭林', '张堰', '朱泾'],
             '长宁': ['北新泾', '古北', '虹桥', '天山', '仙霞', '西郊', '新华路', '镇宁路', '中山公园'],
             '闵行': ['春申', '古美', '航华', '华漕', '静安新城', '金虹桥', '金汇', '老闵行', '龙柏', '马桥', '梅陇', '浦江',
                    '七宝', '吴泾', '莘庄', '颛桥'],
             '青浦': ['白鹤', '重固', '华新', '金泽', '练塘', '香花桥', '夏阳', '徐泾', '盈浦', '赵巷', '朱家角'],
             '静安': ['不夜城', '曹家渡', '大宁', '江宁路', '静安寺', '南京西路', '彭浦', '西藏北路', '阳城', '永和', '闸北公园'],
             '黄浦': ['打浦桥', '董家渡', '淮海中路', '黄浦滨江', '老西门', '南京东路', '蓬莱公园', '人民广场', '世博滨江', '五里桥',
                    '新天地', '豫园']}
